insert into categories ( name, created_at, updated_at) values ('donuts', NOW(), NOW()); 
insert into categories ( name, created_at, updated_at) values ('drinks', NOW(), NOW()); 
insert into categories ( name, created_at, updated_at) values ('kolache', NOW(), NOW()); 
insert into categories ( name, created_at, updated_at) values ('breakfast', NOW(), NOW()); 


 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Beef - Outside, Round', '7/3/2020', '11/23/2020', 1, 14.71, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Sponge Cake Mix - Chocolate', '10/23/2020', '9/3/2020', 1, 11.34, 'Nulla tempus.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Grapes - Green', '12/19/2020', '2/15/2020', 1, 13.41, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Grapefruit - White', '5/29/2020', '1/17/2020', 1, 16.92, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Champagne - Brights, Dry', '9/8/2020', '11/2/2020', 1, 13.19, 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Wine - Red, Antinori Santa', '3/11/2020', '4/17/2020', 1, 11.6, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Beef - Top Sirloin - Aaa', '2/24/2020', '11/19/2020', 1, 4.14, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Bagel - Everything', '12/13/2020', '5/9/2020', 1, 12.28, 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Salami - Genova', '4/8/2020', '1/12/2020', 1, 1.66, 'Vestibulum ac est lacinia nisi venenatis tristique.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Salmon - Canned', '2/2/2020', '10/23/2020', 1, 4.77, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Neckerchief Blck', '2/8/2020', '6/28/2020', 1, 6.41, 'Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Pasta - Penne Primavera, Single', '6/10/2020', '4/29/2020', 1, 12.62, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Filter - Coffee', '11/27/2020', '5/8/2020', 1, 14.46, 'Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Pasta - Ravioli', '12/29/2020', '1/6/2020', 1, 8.05, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Barley - Pearl', '4/20/2020', '8/14/2020', 1, 15.98, 'Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');

 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Pasta - Cheese / Spinach Bauletti', '5/2/2020', '12/6/2020', 2, 17.25, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Pike - Frozen Fillet', '2/22/2020', '11/2/2020', 2, 7.26, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Mix - Cocktail Strawberry Daiquiri', '3/7/2020', '12/4/2020', 2, 1.75, 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Oil - Grapeseed Oil', '10/15/2020', '12/18/2020', 2, 19.7, 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Coffee - Hazelnut Cream', '10/16/2020', '9/5/2020', 2, 7.51, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Wine - Rosso Del Veronese Igt', '2/1/2020', '6/17/2020', 2, 14.93, 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Banana Turning', '3/4/2020', '2/23/2020', 2, 8.73, 'Nulla ut erat id mauris vulputate elementum. Nullam varius.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Wine - Chianti Classico Riserva', '5/30/2020', '2/8/2020', 2, 7.45, 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Beer - True North Lager', '9/8/2020', '11/3/2020', 2, 2.38, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Vodka - Hot, Lnferno', '5/24/2020', '1/20/2020', 2, 2.07, 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Cocktail Napkin Blue', '8/8/2020', '7/11/2020', 2, 2.06, 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Tart - Raisin And Pecan', '6/8/2020', '3/12/2020', 2, 8.52, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Wine - Chardonnay Mondavi', '11/18/2020', '11/16/2020', 2, 19.29, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Crab Brie In Phyllo', '3/23/2020', '12/8/2020', 2, 8.43, 'Suspendisse potenti. In eleifend quam a odio.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Chips Potato Swt Chilli Sour', '8/28/2020', '4/8/2020', 2, 12.38, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.');

 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Chicken Thigh - Bone Out', '3/24/2020', '11/11/2020', 3, 18.55, 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Pea - Snow', '10/17/2020', '2/18/2020', 3, 19.55, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Pepper - Scotch Bonnet', '4/4/2020', '10/10/2020', 3, 3.68, 'Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Beer - Blue Light', '1/28/2020', '5/3/2020', 3, 1.83, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Huck White Towels', '2/26/2020', '3/5/2020', 3, 10.28, 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Chickhen - Chicken Phyllo', '12/8/2020', '1/17/2020', 3, 2.34, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Ostrich - Fan Fillet', '7/15/2020', '8/27/2020', 3, 7.22, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Asparagus - Frozen', '8/29/2020', '3/9/2020', 3, 15.86, 'Duis ac nibh.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Iced Tea - Lemon, 460 Ml', '7/1/2020', '7/2/2020', 3, 12.36, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Muffins - Assorted', '2/29/2020', '1/27/2020', 3, 4.37, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Soap - Pine Sol Floor Cleaner', '3/28/2020', '12/6/2020', 3, 16.02, 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Pheasants - Whole', '6/12/2020', '10/11/2020', 3, 19.87, 'Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Pork - Shoulder', '6/13/2020', '4/26/2020', 3, 12.67, 'Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Garam Masala Powder', '4/22/2020', '3/31/2020', 3, 12.91, 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Sprouts Dikon', '5/9/2020', '7/17/2020', 3, 12.79, 'Fusce consequat. Nulla nisl.');

 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Beer - Maudite', '11/23/2020', '9/27/2020', 4, 18.16, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Cheese - Mozzarella', '4/20/2020', '5/7/2020', 4, 16.78, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Potatoes - Purple, Organic', '2/28/2020', '10/19/2020', 4, 4.07, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Fish - Halibut, Cold Smoked', '12/3/2020', '12/18/2020', 4, 17.93, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Lamb Rack Frenched Australian', '1/6/2020', '1/5/2020', 4, 19.59, 'Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Lamb - Pieces, Diced', '12/25/2020', '12/1/2020', 4, 4.04, 'In blandit ultrices enim.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Pepper - Chili Powder', '7/7/2020', '2/25/2020', 4, 16.52, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Syrup - Monin - Passion Fruit', '11/7/2020', '4/15/2020', 4, 5.42, 'Suspendisse potenti.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Foil - Round Foil', '10/9/2020', '9/1/2020', 4, 3.45, 'Ut at dolor quis odio consequat varius.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Beets - Pickled', '7/6/2020', '9/19/2020', 4, 1.78, 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Tortillas - Flour, 12', '2/23/2020', '7/5/2020', 4, 8.01, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Soup - Campbells, Spinach Crm', '1/10/2020', '5/22/2020', 4, 11.97, 'Morbi porttitor lorem id ligula.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Juice - Orange 1.89l', '4/28/2020', '1/11/2020', 4, 10.2, 'Integer ac leo. Pellentesque ultrices mattis odio.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Creme De Cacao Mcguines', '1/22/2020', '12/28/2020', 4, 3.65, 'Morbi a ipsum. Integer a nibh. In quis justo.');
 insert into menus (name, created_at, updated_at, category_id, price, description) values ('Tea - Herbal Orange Spice', '4/4/2020', '10/1/2020', 4, 16.3, 'Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.');

 insert into options (type, name, price, created_at, updated_at, menu_id) values 
 ('size', 'dozen', 22,NOW(), NOW(), 1);

 insert into options (type, name, price, created_at, updated_at, menu_id) values 
 ('size', 'single', 12,NOW(), NOW(), 1);

